### ISSUE TITLE
UTF8编码

### ISSUE THREAD

**Issue by iphyer** [redspid/LaTeX_note#2]
文件不是UTF8编码，不太适合跨平台。
楼主是不是一直在用纯LaTeX，现在可能用XeLaTeX的更多。

**Comment by redspid** [comment]
对，我一直在用 纯 LaTeX， 前几年看到的 XeLaTeX， 那时候还存在一些问题，就一直没看了。
我大多数工作还是用 windows， 默认编码是GB， 现在的文档我都会手动改成UTF-8编码。

**Comment by iphyer** [comment]
@redspid 谢谢啦！我想这个问题可以解决，主要是 dos2unix即可
